### ISSUE TITLE
Cryptacular 1.6.2 won't install on Python 3.12

### ISSUE THREAD

**Issue by tseaver** [dholth/cryptacular#8]
```bash
$ python3.12 -m venv /tmp/waaaaa
$ /tmp/waaaaa/bin/pip install --upgrade setuptools pip
Collecting setuptools
  Using cached setuptools-69.5.1-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pip in /tmp/waaaaa/lib/python3.12/site-packages (24.0)
Using cached setuptools-69.5.1-py3-none-any.whl (894 kB)
Installing collected packages: setuptools
Successfully installed setuptools-69.5.1
$ /tmp/waaaaa/bin/pip install cryptacular
Collecting cryptacular
  Using cached cryptacular-1.6.2.tar.gz (75 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      scons: Reading SConscript files ...
      ModuleNotFoundError: No module named 'imp':
        File "/tmp/pip-install-d353ck30/cryptacular_a3bab99715974093afced061f9e25d98/SConstruct", line 9:
          import enscons, enscons.cpyext
        File "/tmp/pip-build-env-syq4xj5p/overlay/lib/python3.12/site-packages/enscons/cpyext.py", line 13:
          import imp
      Traceback (most recent call last):
        File "/tmp/waaaaa/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/tmp/waaaaa/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/waaaaa/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-syq4xj5p/overlay/lib/python3.12/site-packages/enscons/api.py", line 35, in prepare_metadata_for_build_wheel
          return _run("dist_info")
                 ^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-syq4xj5p/overlay/lib/python3.12/site-packages/enscons/api.py", line 29, in _run
          lookup = SCons.Node.arg2nodes_lookups[0](alias).sources[0]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: 'NoneType' object has no attribute 'sources'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tseaver** [comment]
This is really just a symptom of https://github.com/dholth/enscons/issues/41 .
